name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ordenar archivos en sus carpetas
        run: |
          mkdir -p src/main/java/com/supertotem
          mkdir -p src/main/resources/assets/supertotem/items
          mkdir -p src/main/resources/assets/supertotem/models/item
          mkdir -p src/main/resources/assets/supertotem/textures/item
          mkdir -p src/main/resources/assets/supertotem/lang
          mv SuperTotemMod.java src/main/java/com/supertotem/
          mv fabric.mod.json src/main/resources/
          mv en_us.json es_es.json src/main/resources/assets/supertotem/lang/
          mv supreme_totem.png src/main/resources/assets/supertotem/textures/item/
          for f in supreme_totem*.json; do
            if grep -q '"parent"' "$f"; then
              mv "$f" src/main/resources/assets/supertotem/models/item/supreme_totem.json
            else
              mv "$f" src/main/resources/assets/supertotem/items/supreme_totem.json
            fi
          done
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12
      - run: gradle build
      - uses: actions/upload-artifact@v4
        with:
          name: supertotem-mod
          path: build/libs/*.jar
